# Generated by Django 5.0.6 on 2024-07-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Writer', '0011_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
